CREATE TABLE ENVIAR_CLIENTE
(
  LOTE Varchar(10),
  CONSECUTIVO Integer,
  OPERACION Varchar(16),
  DOCUMENTO Integer,
  DOCUMENTO_TIPO Varchar(4),
  DOCUMENTO_FECHA Varchar(10),
  NOMBRE_1 Varchar(50),
  NOMBRE_2 Varchar(50),
  APELLIDO_1 Varchar(50),
  APELLIDO_2 Varchar(50),
  FECHA_NACIMIENTO Varchar(10),
  SEXO Varchar(1),
  DIRECCION Varchar(50),
  TELEFONO Varchar(50),
  CELULAR Varchar(50),
  CORREO Varchar(50),
  PAIS Varchar(3),
  DEPTO Varchar(3),
  CIUDAD Varchar(5),
  PAIS_RESIDENCIA Varchar(16),
  DEPTO_RESIDENCIA Varchar(3),
  CIUDAD_RESIDENCIA Varchar(5),
  USUARIO Varchar(16),
  OTRA01 Varchar(4),
  EMPRESA Varchar(250),
  CARGO Varchar(250),
  OCUPACION Varchar(250),
  ADMIN_REC_PUBLIC Varchar(2),
  ACT_ECONOMICA Varchar(250),
  OBSERVACIONES Varchar(250),
  INGRESOS_MENSUALES Integer,
  OTROS_INGRESOS Integer,
  EGRESOS_MENSUALES Integer,
  TOTAL_ACTIVOS Integer,
  TOTAL_PASIVOS Integer,
  SMS Varchar(2),
  OTP Varchar(2),
  FECHA_TRANSACCION Timestamp,
  EMPLEADO_ENTIDAD Varchar(2),
  ES_LEIDO Integer,
  T_INPUT Varchar(10),
  ESTADO Varchar(20),
  ID_ENTIDAD Varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES;

CREATE TABLE ENVIAR_CUENTA
(
  LOTE Varchar(10),
  CONSECUTIVO Integer,
  OPERACION Varchar(16),
  DOCUMENTO Integer,
  CUENTA Varchar(50),
  TIPO Varchar(10),
  TIPO_AHORRO Varchar(2),
  CUENTA_PPAL Varchar(2),
  ESTADO_CUENTA Varchar(20),
  SALDO_TOTAL Integer,
  SALDO_DISPONIBLE Integer,
  PAGO_FECHA Varchar(10),
  PAGO_MIN Integer,
  PAGO_MAX Integer,
  PAGO_REFERENCIA Varchar(50),
  PAGO_MENSAJE Varchar(50),
  FECHA_APERTURA_CUENTA Varchar(10),
  CATEGORIA_GMF Varchar(2),
  SALDO_ACUMULADO Integer,
  USUARIO Varchar(16),
  FECHA_TRANSACCION Timestamp,
  ES_LEIDO Smallint,
  T_INPUT Varchar(10),
  ESTADO Varchar(20),
  ID_ENTIDAD Varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CUENTA TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

 CREATE TABLE ENVIAR_CUENTA_ESTADO
(
  LOTE Varchar(10),
  CONSECUTIVO Integer,
  PROCESO Integer,
  ESTADO Varchar(50),
  ERROR Varchar(250),
  FECHA_REGISTRO Timestamp,
  ES_LEIDO Smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CUENTA_ESTADO TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES;


CREATE TABLE ENVIAR_CUPOS_CANAL
(
  LOTE Varchar(10),
  CONSECUTIVO Integer,
  OPERACION Varchar(10),
  DOCUMENTO Integer,
  CUENTA Varchar(50),
  CANAL Varchar(3),
  NOPE Integer,
  MONTO Integer,
  USUARIO Varchar(16),
  FECHA_TRANSACCION Timestamp,
  ES_LEIDO Smallint,
  TIPO Varchar(2),
  T_INPUT Varchar(10),
  ESTADO Varchar(20),
  ID_ENTIDAD Varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CUPOS_CANAL TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

 CREATE TABLE ENVIAR_CUPOS_CANAL_ESTADO
(
  LOTE Varchar(10),
  CONSECUTIVO Integer,
  PROCESO Integer,
  ESTADO Varchar(50),
  ERROR Varchar(250),
  FECHA_REGISTRO Timestamp,
  ES_LEIDO Smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CUPOS_CANAL_ESTADO TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES;


CREATE TABLE ENVIAR_FINANCIERA
(
  LOTE Varchar(10),
  CONSECUTIVO Integer,
  OPERACION Varchar(16),
  DOCUMENTO Integer,
  CUENTA Varchar(28),
  TIPO Varchar(2),
  TIPO_AH Varchar(2),
  VALOR Integer,
  REFERENCIA Varchar(255),
  USUARIO Varchar(16),
  APLICAR_GMF Varchar(2),
  APLICAR_ACUMULADO Varchar(2),
  FECHA_TRANSACCION Timestamp,
  ES_LEIDO Smallint,
  T_INPUT Varchar(10),
  ESTADO Varchar(20),
  ID_ENTIDAD Varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_FINANCIERA TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

CREATE TABLE ENVIAR_FINANCIERA_ESTADO
(
  LOTE Varchar(10),
  CONSECUTIVO Integer,
  OPERACION Varchar(16),
  DOCUMENTO Integer,
  CUENTA Varchar(28),
  TIPO Varchar(2),
  TIPO_AH Varchar(2),
  VALOR Integer,
  PROCESO Integer,
  ESTADO Varchar(16),
  ERROR Varchar(250),
  FECHA_REGISTRO Timestamp,
  ES_LEIDO Smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_FINANCIERA_ESTADO TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

CREATE TABLE ENVIAR_TARJETA
(
  LOTE Varchar(10),
  CONSECUTIVO Integer,
  OPERACION Varchar(10),
  DOCUMENTO Integer,
  TARJETA Varchar(19),
  USUARIO Varchar(16),
  FECHA_TRANSACCION Timestamp,
  ES_LEIDO Smallint,
  T_INPUT Varchar(10),
  ESTADO Varchar(20),
  ID_ENTIDAD Varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_TARJETA TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

CREATE TABLE ENVIAR_TARJETA_CUENTA
(
  LOTE Varchar(10),
  CONSECUTIVO Integer,
  OPERACION Varchar(10),
  DOCUMENTO Integer,
  CUENTA Varchar(50),
  TIPO Varchar(10),
  TARJETA Varchar(19),
  USUARIO Varchar(16),
  FECHA_TRANSACCION Timestamp,
  ES_LEIDO Smallint,
  T_INPUT Varchar(10),
  ESTADO Varchar(20),
  ID_ENTIDAD Varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_TARJETA_CUENTA TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

 CREATE TABLE ENVIAR_TARJETA_CUENTA_ESTADO
(
  LOTE Varchar(10),
  CONSECUTIVO Integer,
  PROCESO Integer,
  ESTADO Varchar(50),
  ERROR Varchar(250),
  FECHA_REGISTRO Timestamp,
  ES_LEIDO Smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_TARJETA_CUENTA_ESTADO TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES;

CREATE TABLE ENVIAR_TARJETA_ESTADO
(
  LOTE Varchar(10),
  CONSECUTIVO Integer,
  PROCESO Integer,
  ESTADO Varchar(50),
  ERROR Varchar(250),
  FECHA_REGISTRO Timestamp,
  ES_LEIDO Smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_TARJETA_ESTADO TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

CREATE TABLE RECIBIR
(
  ID Varchar(256),
  FECHA_REGISTRO Varchar(8),
  HORA_REGISTRO Varchar(4),
  FECHA Varchar(10),
  HORA Varchar(5),
  FECHA_CONTABLE Varchar(10),
  OPERACION Varchar(16),
  DESCRIPCION Varchar(50),
  SECUENCIA Varchar(50),
  DOCUMENTO Varchar(50),
  CUENTA Varchar(28),
  TIPO Varchar(2),
  TIPO_AH Varchar(2),
  CANAL Varchar(3),
  TERMINAL Varchar(50),
  DISPOSITIVO Varchar(16),
  USUARIO Varchar(16),
  VALOR Integer,
  VALOR_COMISION Integer,
  VALOR_GMF Integer,
  CHEQUE_CODIGO Varchar(255),
  CHEQUE_CUENTA Varchar(50),
  CHEQUE_NUMERO Varchar(50),
  REVERSO Varchar(50),
  ESTADO Varchar(50),
  ERROR Varchar(500),
  TERMINAL_PAIS Varchar(3),
  TERMINAL_DEPARTAMENTO Varchar(4),
  TERMINAL_CIUDAD Varchar(5),
  ORIGEN Varchar(100),
  TIPO_TERMINAL Varchar(250),
  DESCRIPCION_RECAUDO Varchar(250),
  NOMBRE_COMERCIO Varchar(250),
  PSE_REFERENCIA_1 Varchar(250),
  PSE_REFERENCIA_2 Varchar(250),
  ES_LEIDO Smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RECIBIR TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

 CREATE TABLE RECIBIR_CLIENTE
(
  ID Varchar(256),
  FECHA_REGISTRO Varchar(8),
  HORA_REGISTRO Varchar(4),
  FECHA Varchar(10),
  HORA Varchar(5),
  SECUENCIA Varchar(50),
  DOCUMENTO Varchar(50),
  DOCUMENTO_TIPO Varchar(4),
  DOCUMENTO_FECHA Varchar(10),
  NOMBRE_1 Varchar(50),
  NOMBRE_2 Varchar(50),
  APELLIDO_1 Varchar(50),
  APELLIDO_2 Varchar(50),
  FECHA_NACIMIENTO Varchar(10),
  SEXO Varchar(1),
  DIRECCION Varchar(50),
  TELEFONO Varchar(50),
  CELULAR Varchar(50),
  CORREO Varchar(50),
  PAIS Varchar(3),
  DEPTO Varchar(3),
  CIUDAD Varchar(5),
  PAIS_RESIDENCIA Varchar(16),
  DEPTO_RESIDENCIA Varchar(3),
  CIUDAD_RESIDENCIA Varchar(5),
  USUARIO Varchar(16),
  OTRA01 Varchar(4),
  EMPRESA Varchar(250),
  CARGO Varchar(250),
  OCUPACION Varchar(250),
  ADMIN_REC_PUBLIC Varchar(2),
  ACT_ECONOMICA Varchar(250),
  OBSERVACIONES Varchar(250),
  INGRESOS_MENSUALES Integer,
  OTROS_INGRESOS Integer,
  EGRESOS_MENSUALES Integer,
  TOTAL_ACTIVOS Integer,
  TOTAL_PASIVOS Integer,
  ES_LEIDO Smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RECIBIR_CLIENTE TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

 CREATE TABLE RECIBIR_EXTERNA
(
  ID Varchar(256),
  FECHA_REGISTRO Varchar(8),
  HORA_REGISTRO Varchar(4),
  FECHA Varchar(10),
  HORA Varchar(5),
  FECHA_CONTABLE Varchar(10),
  OPERACION Varchar(16),
  DESCRIPCION Varchar(50),
  SECUENCIA Varchar(50),
  DOCUMENTO Varchar(50),
  TERMINAL Varchar(50),
  USUARIO Varchar(16),
  VALOR Integer,
  VALOR_COMISION Integer,
  ESTADO Varchar(50),
  ERROR Varchar(50),
  ES_LEIDO Smallint,
  CHEQUE_CODIGO Varchar(10),
  CHEQUE_CUENTA Varchar(50),
  CHEQUE_NUMERO Varchar(50)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RECIBIR_EXTERNA TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES;

CREATE TABLE RECIBIR_TARJETA_ESTADO
(
  ID Varchar(256),
  FECHA_REGISTRO Varchar(8),
  HORA_REGISTRO Varchar(4),
  FECHA Varchar(10),
  HORA Varchar(5),
  TARJETA Varchar(19),
  ESTADO Varchar(40),
  SERIAL Varchar(32),
  USUARIO Varchar(16),
  ES_LEIDO Smallint,
  ESTADO_DESC Varchar(64)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RECIBIR_TARJETA_ESTADO TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

CREATE TABLE VIRTUAL_CANAL
(
  VICA_ID Integer NOT NULL,
  VICA_CANAL Varchar(3),
  VICA_DESCRIPCION Varchar(250),
  VICA_NOPE Integer,
  VICA_MONTO NUMERICO DEFAULT 0,
  PRIMARY KEY (VICA_ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIRTUAL_CANAL TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES;

CREATE TABLE VIRTUAL_CUENTA
(
  VICU_ID Integer NOT NULL,
  VICU_TIPO_CUENTA Integer,
  VICU_NUMERO_CUENTA Integer,
  VICU_DIGITO_CUENTA Integer,
  VICU_ESTADO Integer,
  VICU_FECHA_REGISTRO Timestamp,
  VICU_FECHA_ACTIVACION Timestamp,
  VICU_ID_AGENCIA Integer,
  PRIMARY KEY (VICU_ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIRTUAL_CUENTA TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

CREATE TABLE VIRTUAL_CUENTA_CANAL
(
  VICC_ID Integer NOT NULL,
  VICU_ID Integer,
  VICA_ID Integer,
  VICC_MONTO NUMERICO DEFAULT 0,
  VICC_NOPE Integer,
  VICC_FECHAREGISTRO Date,
  VICC_ESTADO Integer,
  PRIMARY KEY (VICC_ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIRTUAL_CUENTA_CANAL TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

CREATE TABLE VIRTUAL_TARJETA
(
  VITA_ID Integer NOT NULL,
  VITA_TARJETA Varchar(19) NOT NULL,
  VITA_ASIGNADA BOOLEANO DEFAULT 0,
  VITA_ESTADO TIPOS NOT NULL,
  PRIMARY KEY (VITA_ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIRTUAL_TARJETA TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 

CREATE TABLE VIRTUAL_TARJETA_CUENTA
(
  VITC_ID Integer NOT NULL,
  VICU_ID Integer NOT NULL,
  VITA_ID Integer NOT NULL,
  VITC_ESTADO Integer,
  VITC_FECHAREGISTRO Date,
  PRIMARY KEY (VITC_ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIRTUAL_TARJETA_CUENTA TO  SYSDBA WITH GRANT OPTION;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  CAPTACIONES; 


650498483