TABLAS COODIN

CREATE TABLE ENVIAR_CLIENTE
(
  LOTE varchar(10),
  CONSECUTIVO integer,
  OPERACION varchar(16),
  DOCUMENTO integer,
  DOCUMENTO_TIPO varchar(4),
  DOCUMENTO_FECHA varchar(10),
  NOMBRE_1 varchar(50),
  NOMBRE_2 varchar(50),
  APELLIDO_1 varchar(50),
  APELLIDO_2 varchar(50),
  FECHA_NACIMIENTO varchar(10),
  SEXO varchar(1),
  DIRECCION varchar(50),
  TELEFONO varchar(50),
  CELULAR varchar(50),
  CORREO varchar(50),
  PAIS varchar(3),
  DEPTO varchar(3),
  CIUDAD varchar(5),
  PAIS_RESIDENCIA varchar(16),
  DEPTO_RESIDENCIA varchar(3),
  CIUDAD_RESIDENCIA varchar(5),
  USUARIO varchar(16),
  OTRA01 varchar(4),
  EMPRESA varchar(250),
  CARGO varchar(250),
  OCUPACION varchar(250),
  ADMIN_REC_PUBLIC varchar(2),
  ACT_ECONOMICA varchar(250),
  OBSERVACIONES varchar(250),
  INGRESOS_MENSUALES integer,
  OTROS_INGRESOS integer,
  EGRESOS_MENSUALES integer,
  TOTAL_ACTIVOS integer,
  TOTAL_PASIVOS integer,
  SMS varchar(2),
  OTP varchar(2),
  FECHA_TRANSACCION timestamp,
  EMPLEADO_ENTIDAD varchar(2),
  ES_LEIDO integer,
  T_INPUT varchar(10),
  ESTADO varchar(20),
  ID_ENTIDAD varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CLIENTE TO  SYSDBA WITH GRANT OPTION;

 CREATE TABLE ENVIAR_CUENTA
(
  LOTE varchar(10),
  CONSECUTIVO integer,
  OPERACION varchar(16),
  DOCUMENTO integer,
  CUENTA varchar(50),
  TIPO varchar(10),
  TIPO_AHORRO varchar(2),
  CUENTA_PPAL varchar(2),
  ESTADO_CUENTA varchar(20),
  SALDO_TOTAL integer,
  SALDO_DISPONIBLE integer,
  PAGO_FECHA varchar(10),
  PAGO_MIN integer,
  PAGO_MAX integer,
  PAGO_REFERENCIA varchar(50),
  PAGO_MENSAJE varchar(50),
  FECHA_APERTURA_CUENTA varchar(10),
  CATEGORIA_GMF varchar(2),
  SALDO_ACUMULADO integer,
  USUARIO varchar(16),
  FECHA_TRANSACCION timestamp,
  ES_LEIDO smallint,
  T_INPUT varchar(10),
  ESTADO varchar(20),
  ID_ENTIDAD varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CUENTA TO  SYSDBA WITH GRANT OPTION;


 CREATE TABLE ENVIAR_CUENTA_ESTADO
(
  LOTE varchar(10),
  CONSECUTIVO integer,
  PROCESO integer,
  ESTADO varchar(50),
  ERROR varchar(250),
  FECHA_REGISTRO timestamp,
  ES_LEIDO smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CUENTA_ESTADO TO  SYSDBA WITH GRANT OPTION;


 CREATE TABLE ENVIAR_CUPOS_CANAL
(
  LOTE varchar(10),
  CONSECUTIVO integer,
  OPERACION varchar(10),
  DOCUMENTO integer,
  CUENTA varchar(50),
  CANAL varchar(3),
  NOPE integer,
  MONTO integer,
  USUARIO varchar(16),
  FECHA_TRANSACCION timestamp,
  ES_LEIDO smallint,
  TIPO varchar(2),
  T_INPUT varchar(10),
  ESTADO varchar(20),
  ID_ENTIDAD varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CUPOS_CANAL TO  SYSDBA WITH GRANT OPTION;


 CREATE TABLE ENVIAR_CUPOS_CANAL_ESTADO
(
  LOTE varchar(10),
  CONSECUTIVO integer,
  PROCESO integer,
  ESTADO varchar(50),
  ERROR varchar(250),
  FECHA_REGISTRO timestamp,
  ES_LEIDO smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_CUPOS_CANAL_ESTADO TO  SYSDBA WITH GRANT OPTION;


 ]

CREATE TABLE ENVIAR_FINANCIERA
(
  LOTE varchar(10),
  CONSECUTIVO integer,
  OPERACION varchar(16),
  DOCUMENTO integer,
  CUENTA varchar(28),
  TIPO varchar(2),
  TIPO_AH varchar(2),
  VALOR integer,
  REFERENCIA varchar(255),
  USUARIO varchar(16),
  APLICAR_GMF varchar(2),
  APLICAR_ACUMULADO varchar(2),
  FECHA_TRANSACCION timestamp,
  ES_LEIDO smallint,
  T_INPUT varchar(10),
  ESTADO varchar(20),
  ID_ENTIDAD varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_FINANCIERA TO  SYSDBA WITH GRANT OPTION;

 CREATE TABLE ENVIAR_FINANCIERA_ESTADO
(
  LOTE varchar(10),
  CONSECUTIVO integer,
  OPERACION varchar(16),
  DOCUMENTO integer,
  CUENTA varchar(28),
  TIPO varchar(2),
  TIPO_AH varchar(2),
  VALOR integer,
  PROCESO integer,
  ESTADO varchar(16),
  ERROR varchar(250),
  FECHA_REGISTRO timestamp,
  ES_LEIDO smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_FINANCIERA_ESTADO TO  SYSDBA WITH GRANT OPTION;

 CREATE TABLE ENVIAR_TARJETA
(
  LOTE varchar(10),
  CONSECUTIVO integer,
  OPERACION varchar(10),
  DOCUMENTO integer,
  TARJETA varchar(19),
  USUARIO varchar(16),
  FECHA_TRANSACCION timestamp,
  ES_LEIDO smallint,
  T_INPUT varchar(10),
  ESTADO varchar(20),
  ID_ENTIDAD varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_TARJETA TO  SYSDBA WITH GRANT OPTION;

 CREATE TABLE ENVIAR_TARJETA_CUENTA
(
  LOTE varchar(10),
  CONSECUTIVO integer,
  OPERACION varchar(10),
  DOCUMENTO integer,
  CUENTA varchar(50),
  TIPO varchar(10),
  TARJETA varchar(19),
  USUARIO varchar(16),
  FECHA_TRANSACCION timestamp,
  ES_LEIDO smallint,
  T_INPUT varchar(10),
  ESTADO varchar(20),
  ID_ENTIDAD varchar(8)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_TARJETA_CUENTA TO  SYSDBA WITH GRANT OPTION;


 CREATE TABLE ENVIAR_TARJETA_CUENTA_ESTADO
(
  LOTE varchar(10),
  CONSECUTIVO integer,
  PROCESO integer,
  ESTADO varchar(50),
  ERROR varchar(250),
  FECHA_REGISTRO timestamp,
  ES_LEIDO smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_TARJETA_CUENTA_ESTADO TO  SYSDBA WITH GRANT OPTION;

 CREATE TABLE ENVIAR_TARJETA_ESTADO
(
  LOTE varchar(10),
  CONSECUTIVO integer,
  PROCESO integer,
  ESTADO varchar(50),
  ERROR varchar(250),
  FECHA_REGISTRO timestamp,
  ES_LEIDO smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ENVIAR_TARJETA_ESTADO TO  SYSDBA WITH GRANT OPTION;


 CREATE TABLE RECIBIR
(
  ID varchar(256),
  FECHA_REGISTRO varchar(8),
  HORA_REGISTRO varchar(4),
  FECHA varchar(10),
  HORA varchar(5),
  FECHA_CONTABLE varchar(10),
  OPERACION varchar(16),
  DESCRIPCION varchar(50),
  SECUENCIA varchar(50),
  DOCUMENTO varchar(50),
  CUENTA varchar(28),
  TIPO varchar(2),
  TIPO_AH varchar(2),
  CANAL varchar(3),
  TERMINAL varchar(50),
  DISPOSITIVO varchar(16),
  USUARIO varchar(16),
  VALOR integer,
  VALOR_COMISION integer,
  VALOR_GMF integer,
  CHEQUE_CODIGO varchar(255),
  CHEQUE_CUENTA varchar(50),
  CHEQUE_NUMERO varchar(50),
  REVERSO varchar(50),
  ESTADO varchar(50),
  ERROR varchar(500),
  TERMINAL_PAIS varchar(3),
  TERMINAL_DEPARTAMENTO varchar(4),
  TERMINAL_CIUDAD varchar(5),
  ORIGEN varchar(100),
  TIPO_TERMINAL varchar(250),
  DESCRIPCION_RECAUDO varchar(250),
  NOMBRE_COMERCIO varchar(250),
  PSE_REFERENCIA_1 varchar(250),
  PSE_REFERENCIA_2 varchar(250),
  ES_LEIDO smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RECIBIR TO  SYSDBA WITH GRANT OPTION;

 CREATE TABLE RECIBIR_CLIENTE
(
  ID varchar(256),
  FECHA_REGISTRO varchar(8),
  HORA_REGISTRO varchar(4),
  FECHA varchar(10),
  HORA varchar(5),
  SECUENCIA varchar(50),
  DOCUMENTO varchar(50),
  DOCUMENTO_TIPO varchar(4),
  DOCUMENTO_FECHA varchar(10),
  NOMBRE_1 varchar(50),
  NOMBRE_2 varchar(50),
  APELLIDO_1 varchar(50),
  APELLIDO_2 varchar(50),
  FECHA_NACIMIENTO varchar(10),
  SEXO varchar(1),
  DIRECCION varchar(50),
  TELEFONO varchar(50),
  CELULAR varchar(50),
  CORREO varchar(50),
  PAIS varchar(3),
  DEPTO varchar(3),
  CIUDAD varchar(5),
  PAIS_RESIDENCIA varchar(16),
  DEPTO_RESIDENCIA varchar(3),
  CIUDAD_RESIDENCIA varchar(5),
  USUARIO varchar(16),
  OTRA01 varchar(4),
  EMPRESA varchar(250),
  CARGO varchar(250),
  OCUPACION varchar(250),
  ADMIN_REC_PUBLIC varchar(2),
  ACT_ECONOMICA varchar(250),
  OBSERVACIONES varchar(250),
  INGRESOS_MENSUALES integer,
  OTROS_INGRESOS integer,
  EGRESOS_MENSUALES integer,
  TOTAL_ACTIVOS integer,
  TOTAL_PASIVOS integer,
  ES_LEIDO smallint
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RECIBIR_CLIENTE TO  SYSDBA WITH GRANT OPTION;

 CREATE TABLE RECIBIR_EXTERNA
(
  ID varchar(256),
  FECHA_REGISTRO varchar(8),
  HORA_REGISTRO varchar(4),
  FECHA varchar(10),
  HORA varchar(5),
  FECHA_CONTABLE varchar(10),
  OPERACION varchar(16),
  DESCRIPCION varchar(50),
  SECUENCIA varchar(50),
  DOCUMENTO varchar(50),
  TERMINAL varchar(50),
  USUARIO varchar(16),
  VALOR integer,
  VALOR_COMISION integer,
  ESTADO varchar(50),
  ERROR varchar(50),
  ES_LEIDO smallint,
  CHEQUE_CODIGO varchar(10),
  CHEQUE_CUENTA varchar(50),
  CHEQUE_NUMERO varchar(50)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RECIBIR_EXTERNA TO  SYSDBA WITH GRANT OPTION;

 CREATE TABLE RECIBIR_TARJETA_ESTADO
(
  ID varchar(256),
  FECHA_REGISTRO varchar(8),
  HORA_REGISTRO varchar(4),
  FECHA varchar(10),
  HORA varchar(5),
  TARJETA varchar(19),
  ESTADO varchar(40),
  SERIAL varchar(32),
  USUARIO varchar(16),
  ES_LEIDO smallint,
  ESTADO_DESC varchar(64)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RECIBIR_TARJETA_ESTADO TO  SYSDBA WITH GRANT OPTION;

CREATE GENERATOR VICC_ID_GEN;
SET GENERATOR VICC_ID_GEN TO 0;

CREATE GENERATOR VITC_ID_GEN;
SET GENERATOR VITC_ID_GEN TO 0;

RECREATE TABLE VIRTUAL_LOTE_DIARIO
(
  VLD_ID integer NOT NULL,
  VLD_DESCRIPCION varchar(255),
  VLD_ULTIMA_FECHA date,
  VLD_CONSECUTIVO integer,
  CONSTRAINT VIRTUAL_LOTE_DIARIO_PK PRIMARY KEY (VLD_ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIRTUAL_LOTE_DIARIO TO  SYSDBA WITH GRANT OPTION;

RECREATE TABLE VIRTUAL_CANAL
(
  VICA_ID integer NOT NULL,
  VICA_CANAL varchar(3),
  VICA_DESCRIPCION varchar(250),
  VICA_NOPE integer,
  VICA_MONTO NUMERICO DEFAULT 0,
  VICA_ESLEIDO INTEGER,
  CONSTRAINT VIRTUAL_CANAL_PK PRIMARY KEY (VICA_ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIRTUAL_CANAL TO  SYSDBA WITH GRANT OPTION;

 RECREATE TABLE VIRTUAL_CUENTA
(
  VICU_ID integer NOT NULL,
  VICU_TIPO_CUENTA integer,
  VICU_NUMERO_CUENTA integer,
  VICU_DIGITO_CUENTA integer,
  VICU_ESTADO integer,
  VICU_FECHA_REGISTRO timestamp,
  VICU_FECHA_ACTIVACION timestamp,
  VICU_ID_AGENCIA integer,
  VICU_ESLEIDO INTEGER,
  CONSTRAINT VIRTUAL_CUENTA_PK PRIMARY KEY (VICU_ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIRTUAL_CUENTA TO  SYSDBA WITH GRANT OPTION;

 RECREATE TABLE VIRTUAL_CUENTA_CANAL
(
  VICC_ID integer NOT NULL,
  VICU_ID integer,
  VICA_ID integer,
  VICC_MONTO NUMERICO DEFAULT 0,
  VICC_NOPE integer,
  VICC_FECHAREGISTRO date,
  VICC_ESTADO integer,
  VICC_ESLEIDO INTEGER,
  CONSTRAINT VIRTUAL_CUENTA_CANAL_PK PRIMARY KEY (VICC_ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIRTUAL_CUENTA_CANAL TO  SYSDBA WITH GRANT OPTION;

CREATE GENERATOR VITA_ID_GEN;
SET GENERATOR VITA_ID_GEN TO 0;

 RECREATE TABLE VIRTUAL_TARJETA
(
  VITA_ID integer NOT NULL,
  VITA_TARJETA varchar(19) NOT NULL,
  VITA_ASIGNADA BOOLEANO DEFAULT 0,
  VITA_ESTADO TIPOS NOT NULL,
  VITA_ESLEIDO INTEGER,
  CONSTRAINT VIRTUAL_TARJETA_PK PRIMARY KEY (VITA_ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIRTUAL_TARJETA TO  SYSDBA WITH GRANT OPTION;

 RECREATE TABLE VIRTUAL_TARJETA_CUENTA
(
  VITC_ID integer NOT NULL,
  VICU_ID integer NOT NULL,
  VITA_ID integer NOT NULL,
  VITC_ESTADO integer,
  VITC_FECHAREGISTRO date,
  VITC_ESLEIDO INTEGER,
  CONSTRAINT VIRTUAL_TARJETA_CUENTA_PK PRIMARY KEY (VITC_ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VIRTUAL_TARJETA_CUENTA TO  SYSDBA WITH GRANT OPTION;

SET TERM ^ ;

CREATE TRIGGER VICC_BEFORE_INSERT FOR VIRTUAL_CUENTA_CANAL
ACTIVE BEFORE INSERT POSITION 0
AS 
BEGIN 
  IF (NEW.VICC_ID IS NULL) then
    NEW.VICC_ID = GEN_ID(VICC_ID_GEN,1);
END^

SET TERM ; ^ 

SET TERM ^ ;

CREATE TRIGGER VITC_BEFORE_INSERT FOR VIRTUAL_TARJETA_CUENTA
ACTIVE BEFORE INSERT POSITION 0
AS 
BEGIN 
  IF (NEW.VITC_ID IS NULL) THEN 
    NEW.VITC_ID = GEN_ID(VITC_ID_GEN,1);
END^

SET TERM ; ^ 

SET TERM ^ ;

CREATE TRIGGER VITA_BEFORE_INSERT FOR VIRTUAL_TARJETA
ACTIVE BEFORE INSERT POSITION 0
AS 
BEGIN 
	IF (NEW.VITA_ID IS NULL) THEN 
	  NEW.VITA_ID = GEN_ID(VITA_ID_GEN,1); 
END^

SET TERM ; ^ 
