foldersTree = gFld("<b>ePad(ink)</b>", "", "")
     insDoc(foldersTree, gLnk("Documentation Roadmap", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("api.h", "", "api_8h.html"))
       insDoc(aux1, gLnk("g_IIEPad.idl", "", "g__IIEPad_8idl.html"))
       insDoc(aux1, gLnk("gIIEPad.odl", "", "gIIEPad_8odl.html"))
       insDoc(aux1, gLnk("IePadEnum.idl", "", "IePadEnum_8idl.html"))
       insDoc(aux1, gLnk("provider.idl", "", "provider_8idl.html"))
       insDoc(aux1, gLnk("usb_io.h", "", "usb__io_8h.html"))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("GIIEPADLib::_DGIIEPad", "", "interfaceGIIEPADLib_1_1__DGIIEPad.html"))
       insDoc(aux1, gLnk("GIIEPADLib::_DGIIEPadEvents", "", "interfaceGIIEPADLib_1_1__DGIIEPadEvents.html"))
       insDoc(aux1, gLnk("BACKLIGHT_INFO", "", "structBACKLIGHT__INFO.html"))
       insDoc(aux1, gLnk("DISPLAY", "", "structDISPLAY.html"))
       insDoc(aux1, gLnk("DISPLAY_CAL", "", "structDISPLAY__CAL.html"))
       insDoc(aux1, gLnk("FILTER_CAL", "", "structFILTER__CAL.html"))
       insDoc(aux1, gLnk("gIEDebugGUI", "", "interfacegIEDebugGUI.html"))
       insDoc(aux1, gLnk("gIIEPad", "", "interfacegIIEPad.html"))
       insDoc(aux1, gLnk("GIIEPADLib::GIIEPad", "", "classGIIEPADLib_1_1GIIEPad.html"))
       insDoc(aux1, gLnk("gIIEPadEvent", "", "interfacegIIEPadEvent.html"))
       insDoc(aux1, gLnk("IEPADENUMLib::IEPadEnum", "", "classIEPADENUMLib_1_1IEPadEnum.html"))
       insDoc(aux1, gLnk("IIEPadEnum", "", "interfaceIIEPadEnum.html"))
       insDoc(aux1, gLnk("INK_INFO", "", "structINK__INFO.html"))
       insDoc(aux1, gLnk("IWedge", "", "interfaceIWedge.html"))
       insDoc(aux1, gLnk("LCD_BITMAP", "", "structLCD__BITMAP.html"))
       insDoc(aux1, gLnk("LCD_POINT", "", "structLCD__POINT.html"))
       insDoc(aux1, gLnk("LCD_RECT", "", "structLCD__RECT.html"))
       insDoc(aux1, gLnk("LCD_SCREEN", "", "structLCD__SCREEN.html"))
       insDoc(aux1, gLnk("OPTIONS", "", "structOPTIONS.html"))
       insDoc(aux1, gLnk("SYS_CAL", "", "structSYS__CAL.html"))
       insDoc(aux1, gLnk("T_HANDLE", "", "structT__HANDLE.html"))
       insDoc(aux1, gLnk("tagBACKLIGHTINFO", "", "structtagBACKLIGHTINFO.html"))
       insDoc(aux1, gLnk("tagBITMAP_HEADER", "", "structtagBITMAP__HEADER.html"))
       insDoc(aux1, gLnk("tagBITMAP_REPORT", "", "structtagBITMAP__REPORT.html"))
       insDoc(aux1, gLnk("tagCLRSCRN_REPORT", "", "structtagCLRSCRN__REPORT.html"))
       insDoc(aux1, gLnk("tagDATA_FLAGS", "", "structtagDATA__FLAGS.html"))
       insDoc(aux1, gLnk("tagDATA_REPORT", "", "structtagDATA__REPORT.html"))
       insDoc(aux1, gLnk("tagDISPLAY", "", "structtagDISPLAY.html"))
       insDoc(aux1, gLnk("tagDISPLAY_CAL", "", "structtagDISPLAY__CAL.html"))
       insDoc(aux1, gLnk("tagECHO_REPORT", "", "structtagECHO__REPORT.html"))
       insDoc(aux1, gLnk("tagFILTER_CAL", "", "structtagFILTER__CAL.html"))
       insDoc(aux1, gLnk("tagINK", "", "structtagINK.html"))
       insDoc(aux1, gLnk("tagLAYER", "", "structtagLAYER.html"))
       insDoc(aux1, gLnk("tagLINE_REPORT", "", "structtagLINE__REPORT.html"))
       insDoc(aux1, gLnk("tagMOUSE_REPORT", "", "structtagMOUSE__REPORT.html"))
       insDoc(aux1, gLnk("tagOPTIONS", "", "structtagOPTIONS.html"))
       insDoc(aux1, gLnk("tagOPTIONS_REPORT", "", "structtagOPTIONS__REPORT.html"))
       insDoc(aux1, gLnk("tagPOINT", "", "structtagPOINT.html"))
       insDoc(aux1, gLnk("tagRECT", "", "structtagRECT.html"))
       insDoc(aux1, gLnk("tagRESET_DEFAULTS_REPORT", "", "structtagRESET__DEFAULTS__REPORT.html"))
       insDoc(aux1, gLnk("tagSCRN_HEADER", "", "structtagSCRN__HEADER.html"))
       insDoc(aux1, gLnk("tagSERIALNUM_REPORT", "", "structtagSERIALNUM__REPORT.html"))
       insDoc(aux1, gLnk("tagSYS_CAL", "", "structtagSYS__CAL.html"))
       insDoc(aux1, gLnk("tagSYSCAL_REPORT", "", "structtagSYSCAL__REPORT.html"))
       insDoc(aux1, gLnk("tagTEST_REPORT", "", "structtagTEST__REPORT.html"))
       insDoc(aux1, gLnk("tagWRITE_SCRN_REPORT", "", "structtagWRITE__SCRN__REPORT.html"))
       insDoc(aux1, gLnk("VISIBILITY", "", "structVISIBILITY.html"))
       insDoc(aux1, gLnk("PROVIDERLib::Wedge", "", "classPROVIDERLib_1_1Wedge.html"))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Namespace List", "", "namespaces.html"))
       insDoc(aux1, gLnk("GIIEPADLib", "", "namespaceGIIEPADLib.html"))
       insDoc(aux1, gLnk("IEPADENUMLib", "", "namespaceIEPADENUMLib.html"))
       insDoc(aux1, gLnk("PROVIDERLib", "", "namespacePROVIDERLib.html"))
aux1 = insFld(foldersTree, gFld("Modules", "", "modules.html"))
       insDoc(aux1, gLnk("Generic ePad Access", "", "group__Generic.html"))
       insDoc(aux1, gLnk("Text/Graphics on ePadInk", "", "group__graphLib.html"))
       insDoc(aux1, gLnk("ePadInk - USB level protocol", "", "group__ePadInk__USBIO.html"))
       insDoc(aux1, gLnk("ePadInk - Sample files", "", "group__ePadInk__sampleFiles.html"))
       insDoc(aux1, gLnk("Generic ePad OCX Control", "", "group__gIIEPad.html"))
     insDoc(foldersTree, gLnk("File Members", "", "globals.html"))
     insDoc(foldersTree, gLnk("Namespace Members", "", "namespacemembers.html"))
